# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e5ac123558c00fbb6f0ab24f04fa53de2a100290439a7be0a4fe28c59c15fcb0cd36568b831d75633734e8ece4ac5b1be468f397e75f4685c69746ecf59c42d

test:
  secret_key_base: 8439af4e197f83defa02e439a66946d59a3a6de20dba35a32ae4d7f23ff7c14e6b285adffde4b8467c12128d35dfce2be64b0374b837e21523be8f0957699d0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
